/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportFrame.java
 *
 * Created on Feb 23, 2010, 10:45:44 AM
 */
package petrasys.utils;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import javax.swing.JOptionPane;

/**
 *
 * @author rickcharon
 */
public class ReportFrame extends javax.swing.JFrame implements Runnable {

  private File reportFile;
  private BufferedWriter writer;
  private BlockingQueue reportQueue;

  /** Creates new form ReportFrame */
  public ReportFrame(String fileName, BlockingQueue queueIn) {
    reportQueue = queueIn;
    reportFile = new File(fileName);
    if (!reportFile.exists()) {
      try {
        reportFile.createNewFile();
        writer = new BufferedWriter(new FileWriter(reportFile, true));

      } catch (IOException ex) {
        JOptionPane.showMessageDialog(this, "IO Exception", "ReportFrame ctor", JOptionPane.ERROR_MESSAGE);
      }
    }
    initComponents();
  }

  private synchronized void writeToFile(String str) {
    try {
      writer.write(str);
      writer.flush();
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(this, "IO Exception", "ReportFrame.write()", JOptionPane.ERROR_MESSAGE);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    ReportTextArea = new javax.swing.JTextArea();

    setTitle("PeTraSys Report Window");

    ReportTextArea.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jScrollPane1.setViewportView(ReportTextArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1162, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(53, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new ReportFrame("/share/PeTraSysReports/testingReportFrame", new LinkedBlockingQueue<String>())
                .setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea ReportTextArea;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables

  @Override
  public void run() {
    while (true)
    {
      try
      {
        String msg = reportQueue.take().toString();
        ReportTextArea.append(msg);
        writeToFile(msg);

      }
      catch (InterruptedException ie)
      {
        ie.printStackTrace();
      }
    }
  }
}
