/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DrawDownCalcDlg.java
 *
 * Created on Feb 11, 2010, 4:28:42 PM
 */
package petrasys.indicators.support;

import java.util.Date;
import javax.swing.JLabel;
import petrasys.indicators.DrawDownCalc;

/**
 *
 * @author rickcharon
 */
public class DrawDownCalcDlg extends javax.swing.JDialog {

  String symbol;
  Date beginDate, endDate;

  /** Creates new form DrawDownCalcDlg */
  public DrawDownCalcDlg(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   *
   * @param parent
   * @param modal
   * @param ddc
   * @param symIn
   * @param beginD
   * @param endD
   */
  

  public DrawDownCalcDlg(java.awt.Frame parent, boolean modal, String symIn, Date beginD, Date endD) {
    super(parent, modal);
    this.symbol = symIn;
    this.endDate = endD;
    this.beginDate = beginD;
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    longShortButtonGroup = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    String lstr = "<HTML>DrawDown<BR>Amount<HTML>";
    jLabel1 = new javax.swing.JLabel(lstr);
    DrawDownSpinner = new javax.swing.JSpinner();
    longRadioButton = new javax.swing.JRadioButton();
    shortRadioButton = new javax.swing.JRadioButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    beginDateLabel = new javax.swing.JLabel(beginDate.toString());
    jLabel2 = new javax.swing.JLabel();
    endDateLabel = new javax.swing.JLabel(endDate.toString());
    jPanel3 = new javax.swing.JPanel();
    jLabel4 = new javax.swing.JLabel();
    PeriodsSpinner = new javax.swing.JSpinner();
    doItButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("DrawDown Exploration");
    setModal(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });
    getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPanel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel1.setText("$ DrawDown ");
    jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    jLabel1.setBorder(null);
    jLabel1.setDoubleBuffered(true);
    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jPanel1.add(jLabel1);

    DrawDownSpinner.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    DrawDownSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(300.0d), null, null, Double.valueOf(1.0d)));
    DrawDownSpinner.setAlignmentX(0.0F);
    DrawDownSpinner.setMaximumSize(new java.awt.Dimension(120, 32));
    DrawDownSpinner.setMinimumSize(new java.awt.Dimension(120, 32));
    DrawDownSpinner.setPreferredSize(new java.awt.Dimension(120, 32));
    DrawDownSpinner.setVerifyInputWhenFocusTarget(false);
    jPanel1.add(DrawDownSpinner);

    longShortButtonGroup.add(longRadioButton);
    longRadioButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    longRadioButton.setSelected(true);
    longRadioButton.setText("Long");
    longRadioButton.setAlignmentX(-0.5F);
    jPanel1.add(longRadioButton);

    longShortButtonGroup.add(shortRadioButton);
    shortRadioButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    shortRadioButton.setText("Short");
    shortRadioButton.setAlignmentX(-0.5F);
    jPanel1.add(shortRadioButton);

    getContentPane().add(jPanel1);

    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

    jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    jLabel3.setText("History Being Used:");
    jPanel2.add(jLabel3);

    beginDateLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    beginDateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    beginDateLabel.setMaximumSize(new java.awt.Dimension(350, 32));
    beginDateLabel.setMinimumSize(new java.awt.Dimension(350, 32));
    beginDateLabel.setPreferredSize(new java.awt.Dimension(350, 32));
    jPanel2.add(beginDateLabel);

    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
    jLabel2.setText("to");
    jPanel2.add(jLabel2);

    endDateLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    endDateLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    endDateLabel.setMaximumSize(new java.awt.Dimension(350, 32));
    endDateLabel.setMinimumSize(new java.awt.Dimension(350, 32));
    endDateLabel.setPreferredSize(new java.awt.Dimension(350, 32));
    endDateLabel.setRequestFocusEnabled(false);
    jPanel2.add(endDateLabel);

    getContentPane().add(jPanel2);

    jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

    jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel4.setText("# Look Back Periods:");
    jPanel3.add(jLabel4);

    PeriodsSpinner.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    PeriodsSpinner.setAlignmentX(0.0F);
    PeriodsSpinner.setMaximumSize(new java.awt.Dimension(120, 32));
    PeriodsSpinner.setMinimumSize(new java.awt.Dimension(120, 32));
    PeriodsSpinner.setPreferredSize(new java.awt.Dimension(120, 32));
    PeriodsSpinner.setRequestFocusEnabled(false);
    PeriodsSpinner.setValue(10);
    jPanel3.add(PeriodsSpinner);

    doItButton.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    doItButton.setText("DoIt");
    doItButton.setAlignmentY(1.0F);
    doItButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doItButtonActionPerformed(evt);
      }
    });
    jPanel3.add(doItButton);

    getContentPane().add(jPanel3);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void doItButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doItButtonActionPerformed
      setVisible(false);
    }//GEN-LAST:event_doItButtonActionPerformed


    public Double allowableDrawdown() {
      return Double.parseDouble(DrawDownSpinner.getValue().toString());
    }

    public Boolean goLong() {
      return longRadioButton.isSelected();
    }

    public int periodsLookBack() {
      return Integer.parseInt(PeriodsSpinner.getValue().toString());
    }



  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        DrawDownCalcDlg dialog = new DrawDownCalcDlg(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {

          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSpinner DrawDownSpinner;
  private javax.swing.JSpinner PeriodsSpinner;
  private javax.swing.JLabel beginDateLabel;
  private javax.swing.JButton doItButton;
  private javax.swing.JLabel endDateLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JRadioButton longRadioButton;
  private javax.swing.ButtonGroup longShortButtonGroup;
  private javax.swing.JRadioButton shortRadioButton;
  // End of variables declaration//GEN-END:variables
}
