/*
 *  Copyright (C) 2010 Rick Charon
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * PlayItForward.java
 *
 * Created on Aug 31, 2010, 1:27:19 PM
 */
package petrasys.trader;

import java.util.Date;
import petrasys.instruments.Instrument;

/**
 *
 * @author Rick Charon
 */
public class PlayItForward extends javax.swing.JFrame {

  private Instrument instrument = null;
  private Date tradeDate = null;
  private Integer longShort = 0;
  private Double tradePrice = 0.0;
  private Double profitTarget = 0.0;
  private Double stopLoss = 0.0;

  /** Creates new form PlayItForward */
  public PlayItForward() {
    initComponents();
  }

  public PlayItForward(Instrument instrument, Date tradeDate, 
          Integer longShort, Double tradePrice, Double profitTarget,  Double stopLoss) {
    this();
    this.instrument = instrument;
    this.tradeDate = tradeDate;
    this.longShort = longShort;
    this.tradePrice = tradePrice;
    this.profitTarget = profitTarget;
    this.stopLoss = stopLoss;
  }



  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new PlayItForward().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
