/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DownloadingWaitDlg.java
 *
 * Created on Mar 4, 2010, 9:16:43 AM
 */

package petrasys.connections;

import javax.swing.JLabel;

/**
 *
 * @author rickcharon
 */
public class DownloadingWaitDlg extends javax.swing.JDialog {

    /** Creates new form DownloadingWaitDlg */
    public DownloadingWaitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

        public DownloadingWaitDlg(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    topLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("DownLoading from TWS");
    setAlwaysOnTop(true);
    setBackground(new java.awt.Color(252, 82, 7));
    setUndecorated(true);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    topLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
    topLabel.setText("Data Downloading, Please wait ....");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addComponent(topLabel)
        .addContainerGap(17, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(topLabel)
        .addContainerGap(47, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DownloadingWaitDlg dialog = new DownloadingWaitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  public String getTopLabel() {
    return topLabel.getText();
  }

  public void setTopLabel(String text) {
    this.topLabel.setText(text);
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel topLabel;
  // End of variables declaration//GEN-END:variables

}
