
/*
 * ExpiryDownloadSetup.java
 *
 * Created on Apr 18, 2010, 12:55:25 PM
 */
package petrasys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import petrasys.utils.DBops;
import petrasys.utils.DateOps;
import petrasys.utils.MsgBox;

/**
 *
 * @author rickcharon
 */
public class ExpiryDownloadSetup extends javax.swing.JFrame {

  /** Creates new form ExpiryDownloadSetup */
  public ExpiryDownloadSetup() {
    initComponents();
    setupInitialExpiries();
  }

  public ExpiryDownloadSetup(String ul) {
    this();
    ulTextBox.setText(ul);
  }



  private void setupInitialExpiries() {
    //Date dd = new Date();
    GregorianCalendar gregCal = new GregorianCalendar();
    gregCal.add(Calendar.YEAR, -1);
   // lastExpiryFormatText.setText(DateOps.expiryFormatString(dd));
    //dd.setYear(dd.getYear() - 1);
    beginDateChooser.setDate(gregCal.getTime());
    
    beginExpiryFormatText.setText(DateOps.expiryFormatString(gregCal.getTime()));
  }



  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    ulTextBox = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    daysOffsetTextField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    beginDateChooser = new com.toedter.calendar.JDateChooser();
    goButton = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    beginExpiryFormatText = new javax.swing.JFormattedTextField();
    lastExpiryFormatText = new javax.swing.JFormattedTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Expiry Download Setup");

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel1.setText("Click to set up download expiries for UL:");

    ulTextBox.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    ulTextBox.setText("UL");

    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel2.setText("With days offset:");

    daysOffsetTextField.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    daysOffsetTextField.setText("10");

    jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel3.setText("Begin Date:");
    jLabel3.setEnabled(false);

    beginDateChooser.setEnabled(false);
    beginDateChooser.setFont(new java.awt.Font("DejaVu Sans", 0, 18));

    goButton.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    goButton.setText("GO");
    goButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        goButtonActionPerformed(evt);
      }
    });

    jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel4.setForeground(new java.awt.Color(245, 14, 14));
    jLabel4.setText("NOTE: Put 1 earlier than begin expiry desired for begin expiry, needed to get earliest dates");

    jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel5.setText("Begin Expiry:");

    jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    jLabel6.setText("Last Expiry:");

    beginExpiryFormatText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000000"))));
    beginExpiryFormatText.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    beginExpiryFormatText.setValue(01012010);

    lastExpiryFormatText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("00000000"))));
    lastExpiryFormatText.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
    lastExpiryFormatText.setValue(01012010);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(377, 377, 377)
        .addComponent(goButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(beginDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(23, 23, 23))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel2)
          .addComponent(jLabel1)
          .addComponent(jLabel5)
          .addComponent(jLabel6))
        .addGap(26, 26, 26)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(beginExpiryFormatText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ulTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(daysOffsetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lastExpiryFormatText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(325, Short.MAX_VALUE))
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(35, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel4)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(ulTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(daysOffsetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(beginExpiryFormatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lastExpiryFormatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(goButton)
          .addComponent(jLabel3)
          .addComponent(beginDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(33, 33, 33))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  //rpc - WORKING HERE:4/18/10 1:05 PM - Setup Expiries for continuous download - Not yet fully implemented...
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
      try {
        Connection con = DBops.setuptradesConnection();
        con.setAutoCommit(false);
        int beginExpiry = Integer.parseInt(beginExpiryFormatText.getText());
        int endExpiry = Integer.parseInt(lastExpiryFormatText.getText());
        //beginExpiry = DateOps.expiryFormatInt(beginDateChooserbeginExpiryFormatText.getDate());
        //int endExpiry = DateOps.expiryFormatInt(new Date());
        String ul = ulTextBox.getText();
        PreparedStatement pstmt = DBops.getExpirysForUpdate(con, ul, beginExpiry, endExpiry);
        PreparedStatement upDateStmt = DBops.updateBeginEndDatesForExpiry(con);
        ResultSet res = pstmt.executeQuery();
        int offset = Integer.parseInt(daysOffsetTextField.getText());
        res.next(); //To get a lastexpiry for loop, so should be one extra early expiry
        int lastexp = res.getInt("expiry");
        while (res.next()) {
          int exp = res.getInt("expiry");
          String bdate = DateOps.dbShortFormatString(lastexp - offset);
          String edate = DateOps.dbShortFormatString(exp - offset + 1);
          upDateStmt.setString(1, bdate);
          if (!res.isLast()) {
            upDateStmt.setString(2, edate);
          }
          upDateStmt.setString(3, ul);
          upDateStmt.setInt(4, exp);
          upDateStmt.addBatch();
          lastexp = exp;
        }
        int[] updateCounts = upDateStmt.executeBatch();
        upDateStmt.close();
        con.close();
      } catch (SQLException ex) {
        MsgBox.err2(ex);
      }
    }//GEN-LAST:event_goButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new ExpiryDownloadSetup().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.toedter.calendar.JDateChooser beginDateChooser;
  private javax.swing.JFormattedTextField beginExpiryFormatText;
  private javax.swing.JTextField daysOffsetTextField;
  private javax.swing.JButton goButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JFormattedTextField lastExpiryFormatText;
  private javax.swing.JTextField ulTextBox;
  // End of variables declaration//GEN-END:variables
}
