/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScanIndicators.java
 *
 * Created on Apr 26, 2010, 12:17:42 PM
 */
package petrasys;

import java.util.Vector;
import javax.swing.table.AbstractTableModel;
import petrasys.instruments.RunState;

/**
 *
 * @author rickcharon
 */
public class ScanIndicators extends javax.swing.JFrame {

  

  class indicatorTableModel  extends AbstractTableModel {
    Vector<String> symbols;

    public indicatorTableModel() {
      PeTraSysTopFrame1 top = PeTraSys.getTopFrame();
      symbols = top.getSymbols();
      for(String sym : symbols) {
        top.getSymbolsList().setSelectedValue(sym, false);
        top.setupForActionsOnInstrument("ScanIndicators", RunState.IndicatorScan, null);
        int j = 3;
      }
    }



    public int getRowCount() {
      return symbols.size();
    }

    public int getColumnCount() {
      throw new UnsupportedOperationException("Not supported yet.");
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
      throw new UnsupportedOperationException("Not supported yet.");
    }

  }

  /** Creates new form ScanIndicators */
  public ScanIndicators() {

    indicatorTableModel indTabMod = new indicatorTableModel();
    initComponents();
    indicatorResultsTable.getTableHeader().setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    
  }


  

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    indicatorResultsTable = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    indicatorResultsTable.setFont(new java.awt.Font("DejaVu Sans", 0, 18));
    indicatorResultsTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Symbol", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(indicatorResultsTable);
    indicatorResultsTable.getColumnModel().getColumn(0).setCellEditor(null);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(39, 39, 39)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(60, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new ScanIndicators().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTable indicatorResultsTable;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
